name: Homework Bound - Local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
  - key: exerciseId
    value: ''
  - key: questionId
    value: ''
  - key: worksheetId
    value: ''
color: 120
